name: products_repository
description: Domain and use cases for the app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rest_client:
    path: ../rest_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  freezed: ^2.4.6
