name: app_repository
description: REST Api Usecases for the app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

dependencies:
  app_api_client:
    path: ../app_api_client
  equatable: ^2.0.5
  http: ^1.1.2
